"""Add EstimatedPayroll and EstimatedSettlement tables

Revision ID: 5f74cb88c050
Revises: 
Create Date: 2026-07-16 15:46:03.382104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f74cb88c050'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimated_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=20), nullable=False),
    sa.Column('period_end', sa.String(length=20), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('total_expense', sa.Integer(), nullable=False),
    sa.Column('total_payroll', sa.Integer(), nullable=False),
    sa.Column('other_expense', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimated_settlements_id'), 'estimated_settlements', ['id'], unique=False)
    op.create_table('estimated_payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=20), nullable=False),
    sa.Column('period_end', sa.String(length=20), nullable=False),
    sa.Column('total_work_hours', sa.Float(), nullable=False),
    sa.Column('estimated_salary', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimated_payrolls_id'), 'estimated_payrolls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimated_payrolls_id'), table_name='estimated_payrolls')
    op.drop_table('estimated_payrolls')
    op.drop_index(op.f('ix_estimated_settlements_id'), table_name='estimated_settlements')
    op.drop_table('estimated_settlements')
    # ### end Alembic commands ###
