// [자동 생성] 앞치마 색 변형 이미지 — 마스크 리컬러를 PNG로 구운 것.
// 재생성: scratchpad의 앞치마 생성 스크립트. 손으로 고치지 말 것.
import type { ImageSourcePropType } from 'react-native';

export const APRON_COLORS = ['navy', 'forest', 'wine', 'mustard', 'charcoal', 'terracotta'] as const;
export type ApronColor = (typeof APRON_COLORS)[number];

// mood → 색 → 이미지. 앞치마 색을 착용하면 이 변형이 원본 포즈 PNG를 대체한다.
export const APRON_VARIANTS: Record<string, Partial<Record<ApronColor, ImageSourcePropType>>> = {
  top: { navy: require('../../../assets/mascot/apron/top__navy.webp'), forest: require('../../../assets/mascot/apron/top__forest.webp'), wine: require('../../../assets/mascot/apron/top__wine.webp'), mustard: require('../../../assets/mascot/apron/top__mustard.webp'), charcoal: require('../../../assets/mascot/apron/top__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/top__terracotta.webp') },
  greet: { navy: require('../../../assets/mascot/apron/greet__navy.webp'), forest: require('../../../assets/mascot/apron/greet__forest.webp'), wine: require('../../../assets/mascot/apron/greet__wine.webp'), mustard: require('../../../assets/mascot/apron/greet__mustard.webp'), charcoal: require('../../../assets/mascot/apron/greet__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/greet__terracotta.webp') },
  coffee: { navy: require('../../../assets/mascot/apron/coffee__navy.webp'), forest: require('../../../assets/mascot/apron/coffee__forest.webp'), wine: require('../../../assets/mascot/apron/coffee__wine.webp'), mustard: require('../../../assets/mascot/apron/coffee__mustard.webp'), charcoal: require('../../../assets/mascot/apron/coffee__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/coffee__terracotta.webp') },
  resting: { navy: require('../../../assets/mascot/apron/resting__navy.webp'), forest: require('../../../assets/mascot/apron/resting__forest.webp'), wine: require('../../../assets/mascot/apron/resting__wine.webp'), mustard: require('../../../assets/mascot/apron/resting__mustard.webp'), charcoal: require('../../../assets/mascot/apron/resting__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/resting__terracotta.webp') },
  happy: { navy: require('../../../assets/mascot/apron/happy__navy.webp'), forest: require('../../../assets/mascot/apron/happy__forest.webp'), wine: require('../../../assets/mascot/apron/happy__wine.webp'), mustard: require('../../../assets/mascot/apron/happy__mustard.webp'), charcoal: require('../../../assets/mascot/apron/happy__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/happy__terracotta.webp') },
  welcome: { navy: require('../../../assets/mascot/apron/welcome__navy.webp'), forest: require('../../../assets/mascot/apron/welcome__forest.webp'), wine: require('../../../assets/mascot/apron/welcome__wine.webp'), mustard: require('../../../assets/mascot/apron/welcome__mustard.webp'), charcoal: require('../../../assets/mascot/apron/welcome__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/welcome__terracotta.webp') },
  clipboard: { navy: require('../../../assets/mascot/apron/clipboard__navy.webp'), forest: require('../../../assets/mascot/apron/clipboard__forest.webp'), wine: require('../../../assets/mascot/apron/clipboard__wine.webp'), mustard: require('../../../assets/mascot/apron/clipboard__mustard.webp'), charcoal: require('../../../assets/mascot/apron/clipboard__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/clipboard__terracotta.webp') },
  serving: { navy: require('../../../assets/mascot/apron/serving__navy.webp'), forest: require('../../../assets/mascot/apron/serving__forest.webp'), wine: require('../../../assets/mascot/apron/serving__wine.webp'), mustard: require('../../../assets/mascot/apron/serving__mustard.webp'), charcoal: require('../../../assets/mascot/apron/serving__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/serving__terracotta.webp') },
  pouring: { navy: require('../../../assets/mascot/apron/pouring__navy.webp'), forest: require('../../../assets/mascot/apron/pouring__forest.webp'), wine: require('../../../assets/mascot/apron/pouring__wine.webp'), mustard: require('../../../assets/mascot/apron/pouring__mustard.webp'), charcoal: require('../../../assets/mascot/apron/pouring__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/pouring__terracotta.webp') },
  hero: { navy: require('../../../assets/mascot/apron/hero__navy.webp'), forest: require('../../../assets/mascot/apron/hero__forest.webp'), wine: require('../../../assets/mascot/apron/hero__wine.webp'), mustard: require('../../../assets/mascot/apron/hero__mustard.webp'), charcoal: require('../../../assets/mascot/apron/hero__charcoal.webp'), terracotta: require('../../../assets/mascot/apron/hero__terracotta.webp') },
};
