// [자동 생성] 전신 플립북 — (모션, 앞치마 색)별 스프라이트 시트 1장 + 격자 메타
// 키: 'wave' | 'wave__navy' | ... 기본(갈색)은 색 접미사 없음.
// 재생성: python scripts/bake_mascot.py pack <프레임폴더> → index

import type { FlipSheet } from './Flipbook';

export const FLIP_SHEETS: Record<string, FlipSheet> = {
  'bad': { src: require('../../../assets/mascot/sheets/bad.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__charcoal': { src: require('../../../assets/mascot/sheets/bad__charcoal.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__forest': { src: require('../../../assets/mascot/sheets/bad__forest.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__mustard': { src: require('../../../assets/mascot/sheets/bad__mustard.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__navy': { src: require('../../../assets/mascot/sheets/bad__navy.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__terracotta': { src: require('../../../assets/mascot/sheets/bad__terracotta.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'bad__wine': { src: require('../../../assets/mascot/sheets/bad__wine.webp'), frame: [360, 360], cols: 11, rows: 9, count: 95 },
  'celeb': { src: require('../../../assets/mascot/sheets/celeb.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__charcoal': { src: require('../../../assets/mascot/sheets/celeb__charcoal.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__forest': { src: require('../../../assets/mascot/sheets/celeb__forest.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__mustard': { src: require('../../../assets/mascot/sheets/celeb__mustard.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__navy': { src: require('../../../assets/mascot/sheets/celeb__navy.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__terracotta': { src: require('../../../assets/mascot/sheets/celeb__terracotta.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'celeb__wine': { src: require('../../../assets/mascot/sheets/celeb__wine.webp'), frame: [360, 360], cols: 11, rows: 1, count: 11 },
  'dab': { src: require('../../../assets/mascot/sheets/dab.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__charcoal': { src: require('../../../assets/mascot/sheets/dab__charcoal.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__forest': { src: require('../../../assets/mascot/sheets/dab__forest.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__mustard': { src: require('../../../assets/mascot/sheets/dab__mustard.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__navy': { src: require('../../../assets/mascot/sheets/dab__navy.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__terracotta': { src: require('../../../assets/mascot/sheets/dab__terracotta.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dab__wine': { src: require('../../../assets/mascot/sheets/dab__wine.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance': { src: require('../../../assets/mascot/sheets/dance.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance2': { src: require('../../../assets/mascot/sheets/dance2.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__charcoal': { src: require('../../../assets/mascot/sheets/dance2__charcoal.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__forest': { src: require('../../../assets/mascot/sheets/dance2__forest.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__mustard': { src: require('../../../assets/mascot/sheets/dance2__mustard.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__navy': { src: require('../../../assets/mascot/sheets/dance2__navy.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__terracotta': { src: require('../../../assets/mascot/sheets/dance2__terracotta.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance2__wine': { src: require('../../../assets/mascot/sheets/dance2__wine.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'dance__charcoal': { src: require('../../../assets/mascot/sheets/dance__charcoal.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance__forest': { src: require('../../../assets/mascot/sheets/dance__forest.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance__mustard': { src: require('../../../assets/mascot/sheets/dance__mustard.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance__navy': { src: require('../../../assets/mascot/sheets/dance__navy.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance__terracotta': { src: require('../../../assets/mascot/sheets/dance__terracotta.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'dance__wine': { src: require('../../../assets/mascot/sheets/dance__wine.webp'), frame: [360, 360], cols: 11, rows: 4, count: 38 },
  'heart': { src: require('../../../assets/mascot/sheets/heart.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__charcoal': { src: require('../../../assets/mascot/sheets/heart__charcoal.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__forest': { src: require('../../../assets/mascot/sheets/heart__forest.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__mustard': { src: require('../../../assets/mascot/sheets/heart__mustard.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__navy': { src: require('../../../assets/mascot/sheets/heart__navy.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__terracotta': { src: require('../../../assets/mascot/sheets/heart__terracotta.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'heart__wine': { src: require('../../../assets/mascot/sheets/heart__wine.webp'), frame: [360, 360], cols: 11, rows: 6, count: 61 },
  'jacks': { src: require('../../../assets/mascot/sheets/jacks.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__charcoal': { src: require('../../../assets/mascot/sheets/jacks__charcoal.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__forest': { src: require('../../../assets/mascot/sheets/jacks__forest.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__mustard': { src: require('../../../assets/mascot/sheets/jacks__mustard.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__navy': { src: require('../../../assets/mascot/sheets/jacks__navy.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__terracotta': { src: require('../../../assets/mascot/sheets/jacks__terracotta.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jacks__wine': { src: require('../../../assets/mascot/sheets/jacks__wine.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump': { src: require('../../../assets/mascot/sheets/jump.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__charcoal': { src: require('../../../assets/mascot/sheets/jump__charcoal.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__forest': { src: require('../../../assets/mascot/sheets/jump__forest.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__mustard': { src: require('../../../assets/mascot/sheets/jump__mustard.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__navy': { src: require('../../../assets/mascot/sheets/jump__navy.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__terracotta': { src: require('../../../assets/mascot/sheets/jump__terracotta.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'jump__wine': { src: require('../../../assets/mascot/sheets/jump__wine.webp'), frame: [360, 360], cols: 11, rows: 2, count: 20 },
  'redred': { src: require('../../../assets/mascot/sheets/redred.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__charcoal': { src: require('../../../assets/mascot/sheets/redred__charcoal.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__forest': { src: require('../../../assets/mascot/sheets/redred__forest.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__mustard': { src: require('../../../assets/mascot/sheets/redred__mustard.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__navy': { src: require('../../../assets/mascot/sheets/redred__navy.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__terracotta': { src: require('../../../assets/mascot/sheets/redred__terracotta.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'redred__wine': { src: require('../../../assets/mascot/sheets/redred__wine.webp'), frame: [360, 360], cols: 11, rows: 5, count: 48 },
  'wave': { src: require('../../../assets/mascot/sheets/wave.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__charcoal': { src: require('../../../assets/mascot/sheets/wave__charcoal.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__forest': { src: require('../../../assets/mascot/sheets/wave__forest.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__mustard': { src: require('../../../assets/mascot/sheets/wave__mustard.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__navy': { src: require('../../../assets/mascot/sheets/wave__navy.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__terracotta': { src: require('../../../assets/mascot/sheets/wave__terracotta.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
  'wave__wine': { src: require('../../../assets/mascot/sheets/wave__wine.webp'), frame: [360, 360], cols: 11, rows: 8, count: 82 },
};

// 영상 파이프라인 세트의 원본 재생 속도(fps). 여기 없는 키는 재생기 기본값을 쓴다.
export const FLIP_FPS: Record<string, number> = {
  'bad': 12.0,
  'bad__charcoal': 12.0,
  'bad__forest': 12.0,
  'bad__mustard': 12.0,
  'bad__navy': 12.0,
  'bad__terracotta': 12.0,
  'bad__wine': 12.0,
  'celeb': 24.0,
  'celeb__charcoal': 24.0,
  'celeb__forest': 24.0,
  'celeb__mustard': 24.0,
  'celeb__navy': 24.0,
  'celeb__terracotta': 24.0,
  'celeb__wine': 24.0,
  'dance': 24.0,
  'dance2': 24.0,
  'dance2__charcoal': 24.0,
  'dance2__forest': 24.0,
  'dance2__mustard': 24.0,
  'dance2__navy': 24.0,
  'dance2__terracotta': 24.0,
  'dance2__wine': 24.0,
  'dance__charcoal': 24.0,
  'dance__forest': 24.0,
  'dance__mustard': 24.0,
  'dance__navy': 24.0,
  'dance__terracotta': 24.0,
  'dance__wine': 24.0,
  'heart': 12.0,
  'heart__charcoal': 12.0,
  'heart__forest': 12.0,
  'heart__mustard': 12.0,
  'heart__navy': 12.0,
  'heart__terracotta': 12.0,
  'heart__wine': 12.0,
  'redred': 24.0,
  'redred__charcoal': 24.0,
  'redred__forest': 24.0,
  'redred__mustard': 24.0,
  'redred__navy': 24.0,
  'redred__terracotta': 24.0,
  'redred__wine': 24.0,
  'wave': 24.0,
  'wave__charcoal': 24.0,
  'wave__forest': 24.0,
  'wave__mustard': 24.0,
  'wave__navy': 24.0,
  'wave__terracotta': 24.0,
  'wave__wine': 24.0,
};
